### ISSUE TITLE
I can't see any bulb

### ISSUE THREAD

**Issue by ipa64** [DCMaxxx/LIFX-Widget-v2#1]
Hello,
I've made all step, but I can't see any bulb
Thanks

**Comment by DCMaxxx** [comment]
Hi,

Have you tried to update your bulb to the latest version ?
Another thing, can you get past the tutorial - i.e. you can tap the four icons on the home screen ?

Max.

**Comment by ipa64** [comment]
Hi,
Yes I have updated my bulb to the last version
Yes, I did, yes I can tap the four icons on the home screen.
(I have one LIFX bulb, and one arduino lifx bulb this one can not be updated)

**Comment by DCMaxxx** [comment]
Could you send me a screenshot of your setup in the LIFX app (such as this one: http://a2.mzstatic.com/eu/r30/Purple5/v4/9c/9c/f3/9c9cf3ae-a62a-fd37-ad32-b86c7fafdc9d/screen322x572.jpeg <http://a2.mzstatic.com/eu/r30/Purple5/v4/9c/9c/f3/9c9cf3ae-a62a-fd37-ad32-b86c7fafdc9d/screen322x572.jpeg>), and a screen of the lights screen (http://a3.mzstatic.com/eu/r30/Purple1/v4/6e/42/4c/6e424cbb-8433-25c3-379c-26330f436ec3/screen322x572.jpeg <http://a3.mzstatic.com/eu/r30/Purple1/v4/6e/42/4c/6e424cbb-8433-25c3-379c-26330f436ec3/screen322x572.jpeg>) in LIFX Widget so I can try to reproduce the issue at home ?

**Comment by ipa64** [comment]
Yes here you are
http://i291.photobucket.com/albums/ll286/oneshop1/Ipa64/F630D6E1-5D30-4612-A5DA-ABBC7B9DE6A9.png
http://i291.photobucket.com/albums/ll286/oneshop1/Ipa64/6395BC54-2861-4BBE-B54C-826487266FE4.png

**Comment by DCMaxxx** [comment]
Ok, even with the same name and setup of bulbs, I couldn't reproduce the issue.

Could you run this in your terminal and paste me the output : 
```sh
curl -H "Authorization: Bearer YOUR_APP_TOKEN" "https://api.lifx.com/v1beta1/lights/all"
```
Be sure to replace YOUR_APP_TOKEN with a the token you used in LIFX Widget, or generate a new one on [LIFX Cloud](https://cloud.lifx.com/settings) for test purposes.

**Comment by ipa64** [comment]
Sorry, but what do you mean by "your terminal"?
Thanks for your support

**Comment by DCMaxxx** [comment]
Sorry, I assumed you knew it. Are you using windows or Mac OS X?

**Comment by ipa64** [comment]
Windows

**Comment by DCMaxxx** [comment]
Then simply go to this page : http://api.developer.lifx.com/docs/list-lights

In the "selector" field on the bottom, type "all".
Paste your token when requested, and copy the JSON result here.
It should look like something like that :
[
 {
    "id":...
     ...
 },
 ...
]

Max.

**Comment by ipa64** [comment]
That is what I got
http://i291.photobucket.com/albums/ll286/oneshop1/Ipa64/A3A3EBB1-1936-40E0-A507-687B75480E1F.png

**Comment by DCMaxxx** [comment]
I've removed the link from your answer, since it contains your test token and could potentially control your bulbs over the internet :). You'll probably want to revoke the token as well.

So, from the picture, when we ask for the list of your lights, LIFX tell us that there isn't any. You probably need to add them to your cloud account: Could you try to follow [this steps](https://support.lifx.com/hc/en-us/articles/203711234-Cloud-for-your-LIFX) ?

Let me know how it goes.

**Comment by ipa64** [comment]
Ok so, I've never got the feature to claim my bulb. I think it's because of my arduino lifx strip driver, It is not compliant with last feature. Each time I run the apps, it ask me to update it, so it's maybe why I can not add bulbs to my account, even genuine one.
Thanks to have spend time for my issue!

**Comment by DCMaxxx** [comment]
You might be able to get help via LIFX, but unfortunately, there's nothing I more I can do to help you :(.
As long as your bulb aren't using the clouds' feature, LIFX Widget won't be able to get them.

Maybe LIFX can help though. Do not hesitate to link them this thread, they might be able to get some infos with it.

**Comment by ipa64** [comment]
Yes I understand, very thanks to have spent time

**Comment by DCMaxxx** [comment]
No worries, I hope you'll figure out a solution with them.
